[colophon]
= Preface

This document demonstrates the use of Asciidoc for RISC-V specifications, with the goal of capturing information that will result in effective and efficient collaboration throughout the community.

Asciidoc is the most feature-rich of the popular lightweight markup languages based on Markdown. Most of the markup that you will need is simple, and much is similar to what you use for git-flavored Markdown.

It’s helpful to think of Asciidoc as https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/[Markdown grown up]. People in tech often have impulses to re-invent markdown with a brand new lightweight markup language of their own. As appealing as that idea can be, it is inherently flawed. Publishing, like music, can have simple forms, but when fully featured is quite complex. Everyone who has attempted to build upon Markdown to create a simple and feature-rich publishing solution faces the same reality.

RISC-V specifications require the use of Asciidoc markup and the Asciidoctor toolchain with advanced publishing features that are provided by several add-ons. The templates in this repo are here to allow you to jump in with a hands-on approach and build a pdf using the example files.

Because asciidoc is gaining in popularity, there are opportunities contributors to their specification while it is still being developed. You might want to view what Dan Allen and Sarah White, who support Asciidoctor along with the growing open source community, are currently doing. Feel free to find out about the working group, the specification under development, the various plugins, and ways in which Asciidoc is in use.


[copyright]
.Copyright and licensure

Copyright and license information can go here.
