= Using github actions to build a pdf

This repo contains:

* a demo that can be used for you to implement github actions to build pdfs for RISC-V documentation.
* an example.pdf file that contains helpful information to assist docsumentation contribtors in their authorship.

The github actions requires that you keep specific assets in the same relative location to the build files for the github actions build to work properly, because they pull in information that contains required images, fonts, themes, page formatting, bibliographic information, and other assets.

When you clone this repo, you have the file structure on your machine that you need for creating professional quality pdfs from AsciiDoc, along with examples that demonstrate how to handle use cases that we have encountered.

NOTE: This is a work in progress, and the tools can change, so please let us know if you run into problems and/or have questions.

== Building the example.pdf from github actions

. Navigate to https://github.com/riscv/docs-templates/actions/workflows/build-pdf.yml[github actions] for this repo.
. Click the _Build Document PDF_ button.
. In the _Run workflow_ dropdown that displays, click the down arrow, then click the green _Run workflow_ button in the list.
+ The build starts running and the progress dispalys in the list.
+ Github actions indicates a successful build with a green button, or an unsuccessful build with a red button.

NOTE: If the build is problematic, let us know by emailing help@riscv.org.

== Integrating this build into an existing repo

Some RISC-V contributors are linking directly to the `resources` directory within this docs-temaplates repo. While this is a good idea from the point of view of seamlessly syncing with any style changes that take place over time, this _does not_ give you all of the assets that contribute to the look and feel of RISC-V documentation.

The reason is that the look and feel of PDF output from the toolchain in use is controlled by interactions between the github actions build commmands (contained in files within .github/workflows and /dependencies) and:

* AsciiDoc headers (here in the book_header.adoc).
* Graphics files (here in /images and its subdirectory).
* a YAML theme file (here in /resources/themes).
* fonts (here in /resources/fonts).
* defaults used by Asciidoctor in Prawn.

While best practice is _usually_ to maintain the same relative locations for files and directories so that other contributors can easily find everything, you have the option of changing things for your group and edting the github actions for your repo--as long as the pdf output keeps the esablished looks and feel.

We use the modifier _usually_ because AsciiDoc is intentionally used because of its usefulness in automated environemnts.












