[[tables_graphics]]
== Tables and graphics

Asciidoc makes standard tables easy and also supports the creation of complex tables.


=== Some table examples

AsciiDoc tables can also be created directly from CSV data. Just set the format block attribute to CSV and insert CSV data inside the block delimiters directly:

[source,adoc]
----
[%header,format=csv]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===
----

The above renders as follows:

[%header,format=csv]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===


Here is an additional example of what can be done with tables:

[source,adoc]
----
[cols="e,m,^,>s",width="25%"]
|============================
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|============================
----

Which renders as follows:

[cols="e,m,^,>s",width="25%"]
|============================
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|============================

Code for a numbered encoding table with link target.

NOTE: Annotations have been added to the code to illustrate their use.

[source,adoc]
----
[#proposed-16bit-encodings-1]  <1>
.proposed 16-bit encodings-1    <2>
[width="100%",options=header]
|===
|15 |14 |13 |12 |11 |10 |9 |8 |7 |6 |5 |4 |3 |2 |1 |0 |instruction
3+|100|1|0|0|0 2+|field|0 |0 2+|00 | field 2+|00|mnemonic1
3+|100|1|0|0 3+|field|bit|1 3+|field 2+|00|mnemonic2
3+|110|1|0|0 3+|field|1 |0 3+|field 2+|00|mnemonic3
17+|This row spans the whole table
3+|100|1|1|1 8+|    field        2+| 00  | mnemonic4
|===
----
. Link target.
. Numbered table title.

[#proposed-16bit-encodings-1]
.proposed 16-bit encodings-1
[width="100%",options=header]
|===
|15 |14 |13 |12 |11 |10 |9 |8 |7 |6 |5 |4 |3 |2 |1 |0 |instruction
3+|100|1|0|0|0 2+|field|0 |0 2+|00 | field 2+|00|mnemonic1
3+|100|1|0|0 3+|field|bit|1 3+|field 2+|00|mnemonic2
3+|110|1|0|0 3+|field|1 |0 3+|field 2+|00|mnemonic3
17+|This row spans the whole table
3+|100|1|1|1 8+|    field        2+| 00  | mnemonic4
|===

=== Unicode symbols


For pdf, some unicode symbols are buggy. There are some workarounds. I noticed the need for a mathematical _w_ and because its encoding uses an integer that is in the 5+ digit category it doesn't work.

Here are a few unicode examples from https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references:

As an example, &#9830; is encoded as follows:

```unicode
&#9830;
```

[#useful-unicode]
.Useful unicode for specifications
[width="100%",options=header,format=csv]
|===
sym,num,name
&#9830;,9830,name
&#0034;,0034,name
&#x0077;,0077,w
&#8756;,8756,therefore
&#9839;,9839,sharp
&#1096;,1096,shcy
&#982;,982,piv varpi
&#969;,969,omega
&#8472;,8472,weierp wp
&#8721;,8721,sum
&#8734;,8734,infin
&#8747;,8747,integral
&#8800;,8800,not equal to
&#8804;,8804,le
&#8805;,8805,ge
&#8776;,8776,numerical approximation
&#68;,68,mathematical D?
&#8658;,8658,rightwards double arrow
|===

The fact that some unicode doesn't work is connected to prawn, which is used by asciidoctor-pdf, and not to asciidoctor-pdf itself. The workaround makes use of the fact that it's possible to map fonts to numbers for which you don't need to makeuse of the existing unicode mapping.

If a mathematical _w_ is important, we can implement the workaround until fixes are implemented.


[#unicode-not-working]
.Unicode identified as not working
[width="100%",options=header,format=csv]
|===
sym,num,name
&#9084;,9084,angzarr not working
&#8921;,8921,ggg not working
&#8617;,8617,hookleftarrow not working
|===

=== Graphics

While asciidoc can render graphics in all popular formats, by far the highest quality graphics rendering is from .svg format.

https://wavedrom.com/[Wavedrom sequence diagrams] are essential to the RISC-V specifications. We are in the process of phasing in an automated process for incorporating Wavedrom diagrams into the professional quality pdf output so please stay tuned.

[#wavedrom_example]
.A wavedrom example
image::wavedrom/wavedrom-example.svg[wavedrom_example]

https://asciidoctor.org/docs/asciidoctor-diagram/#image-output-location[Asciidocdoctor-pdf] enables automation of diagrams from scripts, including Wavedrom.

Even as we are using wavedrom to simplify the creation of accurate svgs for register diagrams, the graphical elements--those for the various diagrams--add complexity to the build.

A build that incorporates building of Wavedrom diagrams is under development. The build will support making use of the git repo as the single source of truth for a specification.

Until the automation has been developed ans tested, the code for the wavedrom diagrams should be maintained in the repository and the filename for the SVG output should have the same name (with the SVG extension).


==== Diagram types available

Asciidoctor supports numerous diagram types:



Simple ditaa diagrams:

[source,adoc]
----
[ditaa,target="image-example",svg]
....

                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | SVG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....
----

Renders to:

[ditaa,target="image-example",svg]
....

                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | SVG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

==== Handling Wavedrom diagrams

The following json-formatted script is an example that will be used to generate an svg diagram once the automated process is fully implemented.


[source,wavedrom]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x0, attr: ['ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x04, attr: ['ADD.UW'] },
]}
....


[#wavedrom_example2]
.A second wavedrom example
image::wavedrom/wavedrom-example2.svg[wavedrom_example2]




