---
extends: existence
level: suggestion
link: https://redhat-documentation.github.io/supplementary-style-guide/#_symbols
message: "Do not use the '%s' symbol."
nonword: true
tokens:
  - '(?<![":])\!(?![":])'
  - '(?<!")\&(?!")'
