[[a_few_basics]]
== AsciiDoc basics

AsciiDoc is fully documented, and its documentation is actively maintained. This document contains some information on AsciiDoc markup to get you started.

For details and additional options, see:

 * AsciiDoc/Asciidoctor https://asciidoctor.org/docs/asciidoc-writers-guide/[writers' guide].
 * AsciiDoc http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[quick reference].
 * Asciidoctor http://asciidoctor.org/docs/user-manual/[user manual].

In addition, you can ask questions in the https://discuss.asciidoctor.org/[Asciidoctor discussion list].

As is true of any complex process, AsciiDoc/Asciidoctor has some quirks. Please be certain to use the templates, as the templates provide you with files that result in fully featured PDF output.

Best practice is to test the PDF build frequently to ensure that you have not accidentally introduced something that breaks the build.

WARNING: PDF generation requires the use of Ruby 2.7.2.

[NOTE]
====
Send questions to help@riscv.org.
====

=== Paragraphs

In AsciiDoc, normal paragraphs do not require markup.

To create a new paragraph, put a space after the previous line of text and continue.

==== Basics of blocks and indents

  If you add an indent, your indented text becomes a block like this.

* You can add indented, explanatory paragraphs to lists.
+
Add a `+` directly above the line of text that you want to be indented within the list.
* Another point.
+
Using the `+` to create an indented paragraph works only within the context of a numbered or bulleted list.

AsciiDoc/Asciidoctor supports code blocks with syntax highlighting for many languages. You can use either periods or dashes to indicate code blocks, and use macros to indicate that the block contains code in the specified language, as in the following example:


[source,adoc]
----
[source,python]
....
mono-spaced code block
add a1,a2,a3; # do an ADD
....
----

This example renders as follows:

[source,python]
----
mono-spaced code block
add a1,a2,a3; # do an ADD
----

See <<blocks_notes_markers>> for additional information about blocks.

=== Headers

When you author in AsciiDoc, you cannot jump directly from a Head 1 to a Head 3 or 4. Your headers must appear in sequence from Head 1 to Head 2, and onward. If you skip over a header in the sequence, Asciidoctor throws an error.

The following example is a valid sequence of headers.

```adoc
= Title head (book or report title)

[colophon]
= Colophon head (in frontmatter, used for preface)

[[chapter_title]]
== Head 1 (chapter)

=== Head 2 (section)

==== Head 3 (subsection)

===== Head 4 (sub-subsection)

[appendix]
== Appendix title

[index]
Index
```

NOTE: Settings in the header file (`book_header.adoc` in the docs-templates repo) trigger auto-generation of Appendix prefixes and of the Index (among other things).

=== Lists

Unordered lists are created with the `*` before the list item. Ordered lists require a `.` Add a space between any supporting text at the beginning of a list.

==== Unordered list

To create an unordered list, place a `*` and a space before an item. Put each new list item on a new line. Add a space between any supporting text at the beginning of a list.

* Priv
* Unpriv
* Debug

==== Ordered list

To create an ordered (numbered) list, place a `.` and a space before an item. Put each new list item on a new line. Add a space between any supporting text at the beginning of a list.

. Priv
. Unpriv
. Debug

==== Nested list

To create a nested unordered list, use `** ` before the nested item.

----
* Priv
** Intro
*** Definitions
** CSRs
* Unpriv
----

Which looks like this:

* Priv
** Intro
*** Definitions
** CSRs
* Unpriv

To create a nested ordered list, use `.. ` before the nested list item.

. first item
.. nested item
.. second nested item
. back to original level.

You can also create an unordered list that contains a nested ordered list (or an ordered list that contains a nested unordered list).

* unordered item
.. numbered item
.. second numbered item
* another bullet

==== Add a title to a list

.Ordered list
. Priv
. Unpriv
. Debug

=== Hyperlinks and cross references

Asciidoctor automates some linking as follows:

* Recognizes hyperlinks to Web pages and shortens them for readability.
* Automatically creates an anchor for every section and discrete heading.

==== Hyperlinks

To create highlighted links, use the pattern in the following example:

[source,adoc]
----
https://asciidoctor.org[Asciidoctor]
----

You can set https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-ref/[attributes for your external links]


==== Cross references

Use macros for cross references (links within a document) as in the following example:

[source,adoc]
----
<<Index markers>> describes how index markers work.
----

This example renders as:

<<Index markers>> describes how index markers work.

For more information about options, see https://docs.asciidoctor.org/asciidoc/latest/macros/xref/#internal-cross-references[Cross References].

