[[blocks_notes_markers]]
=== Sidebars

Sidebars provide for a form of commentary.

[source,adoc]
----

****
This is content in a sidebar block.

image:example-3.svg[]

This is more content in the sidebar block.
****
----

This renders as follows:

****
This is content in a sidebar block.

image:example-3.svg[]

This is more content in the sidebar block.
****


You can add a title, along with any kind of content. Best practice for many of the "commentaries" in the LaTeX source that elucidate the decision-making process is to convert to this format with the `TIP` icon that illustrates a conversation or discussion, as in the following example:

[source,adoc]
----
.Optional Title
****
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

TIP: They can contain any type of content, including admonitions like this, and code examples like the following.

.Source code block within a sidebar
[source,js]
/----   (1)
const { expect, expectCalledWith, heredoc } = require('../test/test-utils')
/----  (2)
****

----

1 and 2. Escapes are necessary to preserve this as an AsciiDoc code example.

Once the escapes are removed, the above renders with both the admonition and code blocks within the sidebar:

.Optional Title
****
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

TIP: They can contain any type of content, including admonitions like this, and code examples like the following.

.Source code block in a sidebar
[source,js]
----
const { expect, expectCalledWith, heredoc } = require('../test/test-utils')
----
****

=== Admonition blocks

Five kinds of standard admonition blocks are available in AsciiDoc and these can be mapped to either default or custom icons.

[source,adoc]
----
[NOTE]
====
This is an example of an admonition block.

Unlike an admonition paragraph, it may contain any AsciiDoc content.
The style can be any one of the admonition labels:

* NOTE
* TIP
* WARNING
* CAUTION
* IMPORTANT
====
----

This renders as:

[NOTE]
====
This is an example of an admonition block.

Unlike an admonition paragraph, it may contain any AsciiDoc content.
The style can be any one of the admonition labels:

* NOTE
* TIP
* WARNING
* CAUTION
* IMPORTANT
====

For a single paragraph admonition, simply use a double colon:

[source,adoc]
----
NOTE: Note content.
----

which renders as:

NOTE: Note content.

Alternate octicons:

* alert-24
* comment-discussion-24
* flame-24
* info-24
* pencil-24
* question-24
* sheild-24
* squirrel-24
* zap-24


Another example of an admonition block:

[source,adoc]
----
[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
----

Rendered:

[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====


https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-admonition-icon

The default admonition icons don't look right for RISC-V specification, and alternate icons and colors have been set in risc-v_spec-pdf.yml.  and will be considered.

Current icons, edited to tone down color:

NOTE: note

TIP: tip

WARNING: warning

CAUTION: caution

IMPORTANT: important

[[custom-color-icons]]
.Customized colors for icons
[width="100%",options=header,format=csv]
|===
Icon,default,customized
NOTE,19407c,6489b3
TIP,111111,5g27ag
WARNING,bf6900,9c4d4b
CAUTION,bf3400,c99a2c
IMPORTANT,bf0000,b58f5b
|===

=== Code blocks

AsciiDoc enables code blocks that support syntax highlighting.

For example, preceding a block with a macro `[source,json]` enables `json` syntax highlighting:

[source,json]
----
{
    "weather": {
        "city":       "Zurich",
        "temperature":      25,
    }
}
----

While syntax highlighters for machine code that integrate with the Asciidoctor Ruby toolchain do leave something to be desired, the Rouge highlighter enables line numbers within the code examples.

We are numbering examples as in the following:

[source,adoc]
----
.A spinlock with fences
[source%linenums,asm]
....
          sd           x1, (a1)     # Arbitrary unrelated store
          ld           x2, (a2)     # Arbitrary unrelated load
          li           t0, 1        # Initialize swap value.
      again:
          amoswap.w    t0, t0, (a0) # Attempt to acquire lock.
          fence        r, rw        # Enforce "acquire" memory ordering
          bnez         t0, again    # Retry if held.
          # ...
          # Critical section.
          # ...
          fence        rw, w        # Enforce "release" memory ordering
          amoswap.w    x0, x0, (a0) # Release lock by storing 0.
          sd           x3, (a3)     # Arbitrary unrelated store
          ld           x4, (a4)     # Arbitrary unrelated load
....
----

With the following result:

[[spinlock_fences]]
.A spinlock with fences
[source%linenums,asm]
....
          sd           x1, (a1)     # Arbitrary unrelated store
          ld           x2, (a2)     # Arbitrary unrelated load
          li           t0, 1        # Initialize swap value.
      again:
          amoswap.w    t0, t0, (a0) # Attempt to acquire lock.
          fence        r, rw        # Enforce "acquire" memory ordering
          bnez         t0, again    # Retry if held.
          # ...
          # Critical section.
          # ...
          fence        rw, w        # Enforce "release" memory ordering
          amoswap.w    x0, x0, (a0) # Release lock by storing 0.
          sd           x3, (a3)     # Arbitrary unrelated store
          ld           x4, (a4)     # Arbitrary unrelated load
....


=== Change bars

Change indicators within text files are exceedingly useful and also can be equally complex to implement. Please consider the fact that much of the software programming for Git revolves around handling various kinds of change indicators.

In exploring possible implementation of change bars for RISC-V, we have looked for a solution that is as simple as possible while maximizing value with respect to the time invested in implementing, maintaining, and using the tools and procedures.

The suggested solution makes use of:

- an AsciiDoc `role`.
- modification of two files in the Ruby gem with code snippets (see procedure in the README for https://github.com/riscv/docs-templates).
- Git features.
- a few procedures associated, specifically, with Git updates.

==== Indicate changes

With apologies for requiring a manual step at this time, indicators for the changed lines must be inserted:

[source,adoc]
----
[.Changed]#SELECT clause#

Text without the change bar

[.Changed]#Text with the change bar#
----

[.Changed]#SELECT clause#

Text without the change bar

[.Changed]#Text with the change bar#


For change bars associated with headings, place the change indicator after the heading indicator and before the text, like the following:

----
== [.Changed]#SELECT clause#
----

==== Check for changed lines before a `git commit`

You can double check for all changed lines just before doing a commit, using this pattern:

[source,cmd]
----
git blame <file> | grep -n '^0\{8\} ' | cut -f1 -d:
----

This lists the line numbers of changes within the specified file like the following:

[source,cmd]
----
5
38
109
237
----


=== Footnotes

AsciiDoc has a limitation in that footnotes appear at the end of each chapter. Asciidoctor does not support footnotes appearing at the bottom of each page.

You can add footnotes to your presentation using the footnote macro. If you plan to reference a footnote more than once, use the footnote macro with a target that you identify in the brackets.

[source,adoc]
----
Initiate the hail-and-rainbow protocol at one of three levels:

- doublefootnote:[The double hail-and-rainbow level makes my toes tingle.]
- tertiary
- apocalyptic

A bold statement!footnote:disclaimer[Opinions are my own.]

Another outrageous statement.footnote:disclaimer[]
----

Renders as:

The hail-and-rainbow protocol can be initiated at three levels:

- doublefootnote:[The double hail-and-rainbow level makes my toes tingle.]
- tertiary
- apocalyptic

A bold statement!footnote:disclaimer[Opinions are my own.]

Another outrageous statement.footnote:disclaimer[]
