[[vale-at-riscv]]
== Vale at RISC-V

Vale is an open source linting tool for prose. You can find more about Vale from the https://vale.sh/[Vale website].

RISC-V uses Vale to perform various checks to ensure that the RISC-V style guidelines are followed, ensuring that our documentation is consistent.

You can find installation instructions for Vale at the https://github.com/riscv-admin/riscv-vale/[Vale for RISC-V documentation GitHub repository].

== AsciiDoc style for Vale

The AsciiDoc style for Vale lints common AsciiDoc syntax errors. Note that many of the AsciiDoc rules replicate features of the Visual Studio Code editor Asciidoctor plugin.

Some of the errors that the AsciiDoc rules highlight include:

* Open attribute blocks
* Open quoted ID values
* Images and links that are missing accessibility alt tags
* Missing or incorrect callouts
* Unterminated admonition, listing, and table blocks
* Unbalanced if statements

== RISC-V style for Vale

The RISC-V style for Vale enforces the rules that are set by the RISC-V style guidelines. 

