== Word usage


Above - Avoid using. Above, below, left, and right do not translate well to screen readers. Instead, use "previous or the "following". 

After (once):: Use after to indicate a sequence of events. Use once to indicate one time.

Can (might, must, may, should, shall, will):: 
- Use "can" to indicate capability: "This option can cause your system to fail." 
- Use "might" to indicate possibility: "This option might affect your system performance."
- Don't use "may," which is ambiguous because it could mean either capability or permission.
- Use "should" to indicate a recommended, but optional action. Consider using an alternative phrase instead, such as "we recommend." Do not use "should" to indicate something that might happen. "After you push the power button, the system should turn on." Instead, be bold! "After you push the power button, the system turns on."
- Use "must" to indicate a rquired action or condition. "The system must be powered on."
- Use "shall" to indicate something that "The state of the `BUSY` bit shall change only in response to a write to the register."

If (whether):: Use if as a condition, such as logic. If a, then b.
Use whether to indicate choice or alternative. Event a happens, whether event b does or not.

Legal:: Use only to indicate that something is allowed because of a law. "RISC-V processors are legally available." Avoid using when something is allowed. Instead, use "valid". 

prior (versus "before," "previous," or "preceding"):: 
- If possible, replace "prior" with "before."If you can't use "before," use "prior" as an adjective to refer to something that occurred earlier in time or with a higher order of importance.
- Use "previous" to indicate something that occurred at an unspecified time earlier.
- Use "preceding" to indicate something that occurred immediately beforehand.

Re- words:: In general, words with the prefix `re` can be written without a hyphen. The only exception is `re-create`, unless you are planning to be in a boat having fun.

Since:: Use "since" when time is involved. "Since the invention of sliced bread, toasters became popular." Do not use it when you mean "Because".

Time frame:: Write as 2 words, no hyphen.

